package com.javaproject.client.gui;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kmr2644
 */
public class SignUpForm extends java.awt.Frame {

    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        FormBox = new javax.swing.JPanel();
        IDTextFiled = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDTextFiled1 = new javax.swing.JTextField();
        PWTextField = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        NameTextField = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        IDTextFiled2 = new javax.swing.JTextField();
        signUpButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        FormBox.setBackground(new java.awt.Color(204, 204, 0));

        IDTextFiled.setBackground(new java.awt.Color(204, 204, 0));
        IDTextFiled.setColumns(10);
        IDTextFiled.setForeground(new java.awt.Color(0, 204, 51));
        IDTextFiled.setBorder(null);
        IDTextFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFiledActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("���� ���", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ID");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        IDTextFiled1.setBackground(new java.awt.Color(204, 204, 0));
        IDTextFiled1.setColumns(10);
        IDTextFiled1.setForeground(new java.awt.Color(0, 204, 51));
        IDTextFiled1.setBorder(null);
        IDTextFiled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFiled1ActionPerformed(evt);
            }
        });

        PWTextField.setFont(new java.awt.Font("���� ���", 1, 12)); // NOI18N
        PWTextField.setForeground(new java.awt.Color(102, 102, 102));
        PWTextField.setText("PW");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        NameTextField.setFont(new java.awt.Font("���� ���", 1, 12)); // NOI18N
        NameTextField.setForeground(new java.awt.Color(102, 102, 102));
        NameTextField.setText("Name");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        IDTextFiled2.setBackground(new java.awt.Color(204, 204, 0));
        IDTextFiled2.setColumns(10);
        IDTextFiled2.setForeground(new java.awt.Color(0, 204, 51));
        IDTextFiled2.setBorder(null);
        IDTextFiled2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFiled2ActionPerformed(evt);
            }
        });

        signUpButton.setFont(new java.awt.Font("����", 0, 14)); // NOI18N
        signUpButton.setText("Sign Up!");
        signUpButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FormBoxLayout = new javax.swing.GroupLayout(FormBox);
        FormBox.setLayout(FormBoxLayout);
        FormBoxLayout.setHorizontalGroup(
                FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FormBoxLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(FormBoxLayout.createSequentialGroup()
                                                .addComponent(NameTextField)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(IDTextFiled2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(FormBoxLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormBoxLayout.createSequentialGroup()
                                                                        .addComponent(PWTextField)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(IDTextFiled1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormBoxLayout.createSequentialGroup()
                                                                        .addComponent(jLabel1)
                                                                        .addGap(34, 34, 34)
                                                                        .addComponent(IDTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(FormBoxLayout.createSequentialGroup()
                                                                .addComponent(signUpButton)
                                                                .addGap(66, 66, 66)))))
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        FormBoxLayout.setVerticalGroup(
                FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FormBoxLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(IDTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IDTextFiled1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PWTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FormBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IDTextFiled2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(signUpButton)
                                .addContainerGap())
        );

        add(FormBox, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {
        this.setVisible(false);

    }

    private void IDTextFiled2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void IDTextFiled1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void IDTextFiledActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:ȸ������ �̺�Ʈ
        //LoginForm.userDAO.signUp(IDTextFiled.getText(), IDTextFiled1.getText(), IDTextFiled2.getText());
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify
    private javax.swing.JPanel FormBox;
    private javax.swing.JTextField IDTextFiled;
    private javax.swing.JTextField IDTextFiled1;
    private javax.swing.JTextField IDTextFiled2;
    private javax.swing.JLabel NameTextField;
    private javax.swing.JLabel PWTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton signUpButton;
    // End of variables declaration
}
